### PR TITLE
Accept Throwable for onRejected and expand return type for wait()

### LINKED ISSUE #29: PHPStan level 9 failure
**PHP version**: 7.4 

**Description**
Running PHPStan level 9 checks on this library fails with

```
 ------ -----------------------------------------------------------------------------------------------
  Line   FulfilledPromise.php
 ------ -----------------------------------------------------------------------------------------------
  58     Method Http\Promise\FulfilledPromise::wait() should return T but return statement is missing.
 ------ -----------------------------------------------------------------------------------------------

 ------ ----------------------------------------------------------------------------------------------
  Line   RejectedPromise.php
 ------ ----------------------------------------------------------------------------------------------
  55     Method Http\Promise\RejectedPromise::wait() should return T but return statement is missing.
 ------ ----------------------------------------------------------------------------------------------


 [ERROR] Found 2 errors

```

**How to reproduce**
`phpstan analyze --level 9 src/`

**Possible Solution**
Expand return type of `wait()` to accommodate `void` and `null` return types

### PR DESCRIPTION
**Pull request by Ndiritu**
| Q               | A
| --------------- | ---
| Bug fix?         | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes https://github.com/php-http/promise/issues/29
| Documentation   | if this is a new feature, link to pull request in https://github.com/php-http/documentation that adds relevant documentation
| License         | MIT

#### What's in this PR?

- Corrects the PHPDoc for `wait()` to handle the possible `void` and `null` return values based on the method's description.
- Uses the `\Throwable` interface instead of `\Exception` in `onRejected` callable parameter type
- Adds PHPStan configs and workflow checks to catch future issues early.

#### Checklist

- [x] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix

#### To Do

- [x] Should we consider using conditional return types for `wait()` e.g. `@return ($unwrap is true ? T : null|void)`. This would eliminate further PHPStan failures for dependent libs, however this syntax requires PHPStan `^1.6.0`. Would this be a better approach? At the moment, using `T|null|void` could cause further PHPStan failures for dependent libs. Would these further failures be considered a BC break?

### CODE REVIEW

**Comment by dbu** [comment]
1.6 is from april 2022, so i think that seems reasonable to expect.

lets add that and avoid further confusion for consumers phpstan checks.

File: src/Promise.php [hunk 1]
```diff
@@ -65,7 +65,7 @@ public function getState();
      *
      * @param bool $unwrap Whether to return resolved value / throw reason or not
      *
-     * @return T Resolved value, null if $unwrap is set to false
+     * @return ($unwrap is true ? T : null|void) Resolved value, null if $unwrap is set to false
```
Comment (dbu) [inline src/Promise.php]: how can it return null or void? should this be:
```suggestion
     * @return ($unwrap is true ? T|null : void) Resolved value, or nothing if $unwrap is set to false
```

Comment (Ndiritu) [reply src/Promise.php]: I was guided by https://github.com/php-http/client-common/blob/2.x/src/Deferred.php#L142
Would we need to update client-common to return void instead?

Comment (dbu) [reply src/Promise.php]: afaik its not possible to `return void`. if a method never returns a value, we can use the type declaration `: void` on the method, which makes php realize you can not use the return value. but with this dual use method we can't do that.

if we just `return;` its the same as `return null;` https://3v4l.org/3e3RK

looking at deferred and thinking about this, i think the technically correct doc is

```suggestion
     * @return ($unwrap is true ? T|null : null) Resolved value, null if $unwrap is set to false
```

Comment (Ndiritu) [reply src/Promise.php]: Sorry I meant just `return` instead of `return null`. Interesting didn't realise `return;` implied `return null`, thanks!

`@return ($unwrap is true ? T : null)` should cover a nullable resolve type as well - https://phpstan.org/r/566b7379-3041-438f-86c1-078ee3c95fb8

File: src/FulfilledPromise.php [hunk 2]
```diff
@@ -58,5 +58,6 @@ public function wait($unwrap = true)
         if ($unwrap) {
             return $this->result;
         }
+        return;
```
Comment (Ndiritu) [inline src/FulfilledPromise.php:62]: Implicit `return` added to resolve:
```
------ ---------------------------------------------------------------------------------------------------- 
  Line   FulfilledPromise.php                                                                                
 ------ ---------------------------------------------------------------------------------------------------- 
  :58    Method Http\Promise\FulfilledPromise::wait() should return T|null but return statement is missing.  
 ------ ---------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------- 
  Line   RejectedPromise.php                                                                                
 ------ --------------------------------------------------------------------------------------------------- 
  :55    Method Http\Promise\RejectedPromise::wait() should return T|null but return statement is missing.  
 ------ ---------------------------------------------------------------------------------------------------
```

File: src/Promise.php (hunk 1 above)
Comment (dbu) [reply src/Promise.php]: ah, with `@implements Promise<string|null>` the `@return ($unwrap is true ? T : null)` is enough indeed. and thats the correct way to do it - the promise could also be defined to always have a value or throw an exception, and then there can be no null return when unwrap is true.

**Review by dbu — APPROVED** [review]
thanks a lot!
